### ISSUE TITLE
Splunk config getting old hostname, even if system has been renamed

### ISSUE THREAD

**Issue by lorengordon** [plus3it/splunkforwarder-formula#6]
Solution from the splunk team has been to run these commands and restart the splunk forwarder:

* (Windows) c:\program files\SplunkUniversalForwarder\bin\splunk.exe clone-prep-clear-config
* (Linux) /opt/splunkforwarder/bin/splunk clone-prep-clear-config

However, we do not install splunk using cloned files and do not set anything related to the system hostname in the splunk config, so the forwarder _should_ be getting what it is _supposed_ to get anyway during it's first-time run. Which means that even if we run this command and restart the service, we may _still_ get the old name (at least, prior to a reboot).

Anyway, something to test.

Possibly helpful article: https://answers.splunk.com/answers/452782/how-is-server-identified-after-clone-prep-clear-co.html

**Comment by ferricoxide** [comment]
This is likely to come down to an ordering issue. Need a method to ensure that the hostname-setting formula executes first (and that it changes not only the rebooted-to hostname but the current-epoch's hostname).

To be honest, this mess could be "fixed" (avoided, actually) if cloud-config's native hostname-setting were used instead of doing things quite so after the fact. Obviously, I'm aware that such recommendation doesn't solve the Windows problem nor does it address the "execute the same way regardless of Windows-vs-Linux" goal. Just pointing out the pitfalls of reinventing the wheel.

**Comment by lorengordon** [comment]
Fairly sure this is an issue only on Windows, since the hostname doesn't really change until after a reboot. The Linux side of the report appears to have been due to user error. Patch inbound for Windows...
